{ mkFeature, ... }:

mkFeature {
  name = "wezterm";
  homeManager =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.programs.wezterm;
      hasSettings = cfg.settings != { };
    in
    {
      imports = [ ./settings.nix ];

      programs.wezterm.enable = lib.mkDefault pkgs.stdenv.isLinux;
      programs.wezterm.extraConfig = lib.mkBefore (builtins.readFile ./behavior.lua);

      # Home Manager writes this file itself when WezTerm is enabled.
      # Keep its settings and extraConfig merge behavior without installing a package.
      xdg.configFile."wezterm/wezterm.lua" =
        lib.mkIf (!cfg.enable && (hasSettings || cfg.extraConfig != ""))
          {
            text =
              if hasSettings then
                ''
                  -- Generated by Home Manager.
                  -- See https://wezfurlong.org/wezterm/

                  local wezterm = require 'wezterm'
                  local config = wezterm.config_builder and wezterm.config_builder() or {}

                  local hm_config = ${lib.generators.toLua { } cfg.settings}
                  for k, v in pairs(hm_config) do
                    config[k] = v
                  end

                  ${lib.optionalString (cfg.extraConfig != "") ''
                    local _hm_extra = (function()
                      ${cfg.extraConfig}
                    end)()
                    if type(_hm_extra) == "table" then
                      for k, v in pairs(_hm_extra) do
                        config[k] = v
                      end
                    end
                  ''}
                  return config
                ''
              else
                ''
                  -- Generated by Home Manager.
                  -- See https://wezfurlong.org/wezterm/

                  local wezterm = require 'wezterm'

                  ${cfg.extraConfig}
                '';
          };
    };
}
