{
  imports = [
    ./autopairs.nix
    ./cmp.nix
    ./comment.nix
    ./conform.nix
    ./indent-blankline.nix
    ./lazy.nix
    ./lsp.nix
    ./lualine.nix
    ./nvim-tree.nix
    ./oil.nix
    ./persistence.nix
    ./smart-splits.nix
    ./telescope.nix
    ./treesitter.nix
    ./ts-context-commentstring.nix
  ];
}
