{
  imports = [
    ./autopairs.nix
    ./ts-autotag.nix
    ./cmp.nix
    ./comment.nix
    ./conform.nix
    ./git-conflict.nix
    ./gitsigns.nix
    ./indent-blankline.nix
    ./lazy.nix
    ./lsp.nix
    ./lualine.nix
    ./none-ls.nix
    ./nvim-tree.nix
    ./oil.nix
    ./persistence.nix
    ./smart-splits.nix
    ./telescope.nix
    ./treesitter.nix
    ./ts-context-commentstring.nix
    ./typescript-tools.nix
    ./ufo.nix
    ./which-key.nix
  ];
}
